### ISSUE TITLE
Modbus RTU over TCP 

### ISSUE THREAD

**Issue by ccatterina** [AdvancedClimateSystems/uModbus#51]
Hi,
Is there a way to send RTU messages through TCP?
I need this functionality because we usually convert all the serial devices with rs485/ethernet converter.

**Comment by OrangeTux** [comment]
From what I understand you want have a Modbus RTU Master that needs to send requests to Modbus TCP slave. Is that correct?

**Comment by ccatterina** [comment]
No, i have a Modbus TCP master (my raspberrypi) that needs to send requests to a Modbus RTU slave, in the middle there is a rs485/ethernet converter that receives the requests from the raspberry and sends them to the slave through the serial line.

**Comment by OrangeTux** [comment]
This is no problem. I've build one myself using the building blocks that uModbus provides. 

As you may know Modbus RTU and Modbus TCP have a few bytes in common, the PDU. As shown in [this image](http://www.simplymodbus.ca/images/adu_pdu.PNG).

To convert a Modbus TCP request into a Modbus RTU request you need to strip the MBAP header and add a CRC. After you receive the RTU response you need remove the CRC and prepend the message with the MBAP header and return that.

**Comment by ccatterina** [comment]
Thank you very much. That's all I needed.

I close the iusse.

**Comment by rahimdzb** [comment]
Does

> D'après ce que j'ai compris, vous avez un maître Modbus RTU qui doit envoyer des requêtes à l'esclave Modbus TCP. Est-ce exacte ?
In this case what we do exactly !
