### ISSUE TITLE
Unresolved references in simple_rtu_data_store

### ISSUE THREAD

**Issue by jdt1** [AdvancedClimateSystems/uModbus#71]
I ran across some issues while trying to use simple_rtu_data_store.py

line 9 log_to_stream is not defined
and
line 15 conf is not defined

Also it seems rtu.get_server does not exist anymore but instead get_server should be imported from umodbus.server.serial.

Hope this is useful.

**Comment by OrangeTux** [comment]
Thanks for your comment! 

`simple_rtu_data_store.py` is outdated and had to be removed.But for some reason it never was deleted. It has been replaced by `simple_rtu_server.py`.

Thanks again, I will remove the script.
