### ISSUE TITLE
DeprecationWarning: inspect.getargspec() is deprecated

### ISSUE THREAD

**Issue by afi-lambda** [AdvancedClimateSystems/uModbus#76]
When using rtu.send_message() of your lib with Python 3.6.6 and pytest, I have a warning:

...\venv\lib\site-packages\umodbus\functions.py:129: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()

Modifiying line 129 of functions.py from:
    ...inspect.getargspec(...
to:
    ...inspect.getfullargspec(...
remove the warning in my case

Perhaps you could integrate this change in your code

**Comment by OrangeTux** [comment]
Thanks for your notification!
