### ISSUE TITLE
Adding support for string datatype

### ISSUE THREAD

**Issue by akshaykhushu** [AdvancedClimateSystems/uModbus#95]
Is there any plan of adding support for string datatype to uModbus?

If not are there any other libraries like uModbus with support for string?

**Comment by OrangeTux** [comment]
Modbus doens't have a string type. Only uint16 (registers) and booleans (coils). So no, uModbus won't implement a string type. 
If you want to send strings you need to implement them self on on top of uint16 and/or coils.
