### ISSUE TITLE
Can this be used for Modbus sniffing?

### ISSUE THREAD

**Issue by vshymanskyy** [AdvancedClimateSystems/uModbus#96]
One interesting application of this could be to be able to attach to an existing Modbus connection (just the RX line), and to be able to decode/display the messages.
Wondering if any additional development is needed to achieve this.

**Comment by OrangeTux** [comment]
I guess you want to sniff on Modbus RTU communication, correct? That would be possible. 

I think I would override `RTUServer.execute_route()` to decode and display the messages.

``` python
def execute_route(self, meta_data, request_pdu):
    function = create_function_from_request_pdu(request_pdu)
    print(function)
```

**Comment by OrangeTux** [comment]
Closed due to inactivity. Feel free to reopen if needed.
